LearnStock/urls.py
from django.contrib import admin
from django.urls import path
from stock import views
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.urls import reverse

class MyRegistrationView(RegistrationView): 
    def get_success_url(self, user):
         return reverse('stock:register_profile')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('stock/',include('stock.urls')),
    path('accounts/register/', MyRegistrationView.as_view(),name='registration_register'),
    path('accounts/',include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/urls.py
from django.urls import path
from stock import views


app_name ='stock'

urlpatterns = [
    path('stock/',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('category/<slug:category_name_slug>/',
         views.show_category, name='show_category'),
    path('add_category/',views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/',views.add_page,name='add_page'),
    #path('register/', views.register, name='register'),
    #path('login/',views.user_login, name='login'),
    path('restricted/',views.restricted,name='restricted'),
    #path('logout/',views.user_logout,name='logout'),
    path('goto/',views.goto_url, name='goto'),
    path('register_profile/',views.register_profile,name='register_profile'),
    path('News',views.News,name='News'),
    path('add_comment/<slug:category_name_slug>/', views.add_comment, name='add_comment'),
    path('search',views.search,name='search'),
    path('like_category/', views.LikeCategoryView.as_view(), name='like_category'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
]

stock/models.py
from django.db import models
from django.db.models.fields import SlugField
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
# category model
class Category(models.Model):
    name = models.CharField(max_length=128,unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(Category,self).save(*args,**kwargs)
        

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

# page model
class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

# userprofile model
class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images',blank=True)

    def __str__(self):
        return self.user.username

# comment model     
class Comment(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    username = models.CharField(max_length=12)
    content = models.CharField(max_length=128)
    posttime = models.DateTimeField(default = datetime.now())
    category = models.SlugField()

stock/forms.py
from django import forms
from stock.models import Page,Category, UserProfile
from django.contrib.auth.models import User
from stock.models import Comment

# the form for category
class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text=" please enter the category name")
    views = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(),required=False)

    class Meta:
        model= Category
        fields=('name',)

# the form for page
class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="please enter the title of page.")
    url = forms.URLField(max_length=200,
                            help_text="please enter the URL of the page.")
    views = forms.IntegerField(widget= forms.HiddenInput(),initial=0)

    class Meta:
        model = Page
        exclude=('category',)
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url']=url

        return cleaned_data

# the form for user
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')

# the form for userprofile
class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)
    
    class Meta:
        model = UserProfile
        fields = ('website','picture',)

# the form for comment
class CommentForm(forms.ModelForm):
    content = forms.CharField(max_length=500)
    class Meta:
        model = Comment
        fields = ('content',)

stock/views.py
from django.core.exceptions import NON_FIELD_ERRORS
from django.shortcuts import render
from django.http import HttpResponse
from stock.bing_search import run_query
from stock.models import Category
from stock.models import Page,Comment
from stock.forms import CategoryForm, PageForm
from django.shortcuts import redirect
from django.urls import reverse
from stock.forms import UserForm, UserProfileForm,CommentForm
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime
from django.contrib.auth.models import User 
from stock.models import UserProfile
from django.utils.decorators import method_decorator
from django.views import View


# Create your views here.

# the view of cookie
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request,'visits','1'))
    last_visit_cookie = get_server_side_cookie(request,'last_visit',str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')

    if(datetime.now() - last_visit_time).days > 0 :
        visits= visits+1
        request.session['last_visit']=str(datetime.now())
    else:
        request.session['last_visit']=last_visit_cookie
    request.session['visits'] =visits

# the view of homepage
def index(request):
    category_list=Category.objects.order_by('-likes')[:5]
    page_list=Page.objects.order_by('-views')[:4]
    context_dict={}
    #context_dict['boldmessage']:' hi, julia '
    context_dict['categories']=category_list
    context_dict['pages']=page_list
    
    visitor_cookie_handler(request)
    context_dict['visits']=request.session['visits']

    response = render(request,'stock/index.html',context=context_dict)
    
    return response
    

def about(request):
    #context_dict = {}
    #visitor_cookie_handler(request)
    #context_dict['visits']= request.session['visits']
    
    #print(request.method)
    #print(request.user)
    #if request.session.test_cookie_worked():
     #   print("TEST COOKIE WORKED!")
      #  request.session.delete_test_cookie()

    return render(request,'stock/about.html')


# the view of show the category
def show_category(request,category_name_slug):
    context_dict={}
    
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)

        context_dict['pages']=pages
        context_dict['category']=category
    except Category.DoesNotExist:
        context_dict['pages']=None
        context_dict['category']=None
    form = CommentForm()
    context_dict['form']=form
        
    
    try:
        comment = Comment.objects.filter(category=category_name_slug).order_by('-posttime')[:6]
        context_dict['comments'] = comment
    except Comment.DoesNotExist:
        context_dict['comments'] = None
    
    return render(request,'stock/category.html',context=context_dict)

# the view of function add new category
@login_required
def add_category(request):
    form = CategoryForm()

    if request.method =='POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            this_category=form.save(commit=True)
            this_category.views=0
            this_category.likes=0
            this_category.save()
            print(this_category)

            return redirect('stock:News')
        else:
            print(form.errors)
    return render(request,'stock/add_category.html',{'form':form})

# the view of function add new page
@login_required
def add_page(request,category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None

    if category is None:
        return redirect('/index/')

    form = PageForm()
    
    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('stock:show_category',kwargs={'category_name_slug':category_name_slug}))
        else:
            print(form.errors)
    context_dict={'form':form,'category':category}
    return render(request,'stock/add_page.html',context=context_dict)


#def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form=UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered= True
        else:
            print(user_form.errors,profile_form.errors)
    else:
            user_form = UserForm() 
            profile_form = UserProfileForm() 

    return render(request,'stock/register.html',
                     context = {'user_form':user_form,
                       'profile_form':profile_form,
                       'registered':registered})

#def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return redirect(reverse('index'))
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print(f"Invalid login details:{username},{password}")
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request,'stock/login.html')

# the view of simuilator page, has a login required
@login_required
def restricted(request):
    return render(request,'stock/restricted.html')

@login_required
#def user_logout(request):
 #   logout(request)
  #  return redirect(reverse('stock:index'))





def goto_url(request):
    if request.method == 'GET':
            page_id = request.GET.get('page_id')

            try:
                selected_page = Page.objects.get(id=page_id)
            except Page.DoesNotExist:
                return redirect(reverse('stock:index'))

            selected_page.views = selected_page.views + 1
            selected_page.save()
            

            return redirect(selected_page.url)
          
    return redirect(reverse('stock:index'))


@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST,request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect(reverse('index'))
        else:
            print(form.errors)
    context_dict={'forms':form}
    return render(request,'stock/profile_registration.html',context_dict)

# the view of news page
def News(request):
    category_list=Category.objects.order_by('-likes')
    page_list=Page.objects.order_by('-views')
    context_dict={}
    #context_dict['boldmessage']:' hi, julia '
    context_dict['categories']=category_list
    context_dict['pages']=page_list

    
    return render(request,'stock/News.html',context=context_dict)

      
# the view of add comment
def add_comment(request, category_name_slug):
    form = CommentForm(request.POST)
    if form.is_valid() and form['content'] != None:
        f = form.save(commit=False)
        f.username = get_server_side_cookie(request, 'username', 'Anonym')
        f.username = request.user.username # temporary solution for comment username
        f.posttime = datetime.now()
        f.category = category_name_slug
        f.save()

        # for redirect back to the page after refresh
        return redirect(f'/stock/category/{category_name_slug}')
    else:
        print(form.errors)


  

#class AboutView(View):
    def get(self,request):
        context_dict={}

        visitor_cookie_handler(request)
        context_dict['visits']=request.session['visits']

        return render(request,'stock/about.html',context_dict)


class ProfileView(View):
    def get_user_details(self, username):
        try:
           user = User.objects.get(username=username)
        except User.DoesNotExist: 
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'website': user_profile.website,
                                'picture': user_profile.picture}) 
        return (user, user_profile, form)

    @method_decorator(login_required) 
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('stock:index'))
        
        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'stock/profile.html', context_dict)

    @method_decorator(login_required) 
    def post(self, request, username):
       try:
        (user, user_profile, form) = self.get_user_details(username)
       except TypeError:
        return redirect(reverse('stock:index'))
       form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

       if form.is_valid():
        form.save(commit=True)
        return redirect('stock:profile', user.username)
       else: 

templates/stock/about.html
{%extends 'stock/base2.html'%} 
{% load staticfiles %}



{% block title_block %}
        Stock
{% endblock %}

{%  block body_block %}
          Stock says...
    <div>
      <h1> here is the about page. </h1><br />

    </div>
    <div>
            <img src="{% static 'images/neipoint.jpg' %}" alt="Picture of st.sea" />
            
    </div>
{% endblock %}

templates/stock/about1.html
<!DOCTYPE html>
{% load staticfiles %}
{% load stock_template_tags %}


<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Stock</title>
        <link rel="icon" type="image/x-icon" href="static/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="static/css/styles.css" rel="stylesheet" />
    </head>
  
    <body>
        <!-- Navigation-->
       
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'index' %}">    StockLearn
                  
                    {% block title_block %}
                     
                    {% endblock %}   </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                   
                   
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'index' %}">Home</a></li>  
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'stock:about' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'stock:News' %}">News</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'stock:search' %}">Search</a></li>  
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'stock:restricted' %}">Simulator</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'auth_logout' %}?next={% url 'index'%}">Logout</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'stock:add_category' %}">Add A New Category</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'auth_password_change' %}">Change Your Password</a></li>
                        
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'stock:restricted' %}">Simulator</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'auth_login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'registration_register' %}">Sign up</a></li>
                        {% endif %}
                    </ul>
                </div>
              
            </div>
            <li>
                {% if user.is_authenticated %} 
                <div>
                <a class="navbar-brand"  >
                Dear {{ user.username }}
                {% else %}    
                <a class="navbar-brand"  > Welcome！</a>
                {% endif %}</a>
            </div></li>
        </nav>
       

        <!-- Page Header-->
        <header class="masthead" style="background-image: url('static/assets/img/about-bg.jpg');height:200px">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>LearnStock</h1>
                            <span class="subheading">This is the best application for studying stock</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>



        
        {% block body_block %}
        <!-- Main Content-->
      

        {% endblock %}

        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; LearnStock 2021</div>
                        <div class="small text-center text-muted fst-italic">For help, please contact Yueyue Liu </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="static/js/scripts.js"></script>
    </body>
</html>

templates/stock/base1.html
<!DOCTYPE html>
{% load staticfiles %}
{% load stock_template_tags %}


<html lang="en">
    <head>
      
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Stock</title>
        <link rel="icon" type="image/x-icon" href="static/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="static/css/styles.css" rel="stylesheet" />
        <style>   
       .topnav {
        overflow: hidden;
        background-color:#c4e1ff;
        opacity:0.6;
        font-size: x-large;
        }
       .topnav a {
       float: left;
       display: block;
       color: #f2f2f2;
       text-align: center;
       padding: 25px 20px;
       text-decoration: none;
       }
       .topnav a:hover {
       background-color:rgb(255, 255, 255);
       color: black;
       }
       </style>
    </head>
  
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}"> StockLearn
                    {% block title_block %}
                    {% endblock %}   </a>
                
                <div class="topnav text-align: center">
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    
                    <ul class="navbar-nav">
                        <a class="nav-link">     </a> 
                        <a class="nav-link " href="{% url 'index' %}">Home</a>  
                        <a class="nav-link" href="{% url 'stock:about' %}">About</a>
                        <a class="nav-link" href="{% url 'stock:News' %}">News</a>
                        <a class="nav-link" href="{% url 'stock:search' %}">Search</a>
                        {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'stock:restricted' %}">Simulator</a>
                        <a class="nav-link" href="{% url 'stock:add_category' %}">Add A New Category</a>
                        <a class="nav-link" href="{% url 'stock:profile' user.username %}">Profile</a>
                        <a class="nav-link" href="{% url 'auth_logout' %}?next={% url 'index'%}">Logout</a>
                       
                        {% else %}
                        <a class="nav-link " href="{% url 'stock:restricted' %}">Simulator</a>
                        <a class="nav-link " href="{% url 'auth_login' %}">Login</a>
                        <a class="nav-link " href="{% url 'registration_register' %}">Sign up</a>
                        {% endif %}
                        <a class="nav-link">   </a> 
                    </ul>
                
                </div>
                </div> 
            </div>

            <li>
                {% if user.is_authenticated %} 
                <div>
                <a class="navbar-brand">
                Dear {{ user.username }}
                {% else %}    
                <a class="navbar-brand"> Welcome！</a>
                {% endif %}</a>
               </div>
            </li>
        </nav>

        <!-- Page Header-->
        <header class="masthead" style="background-image: url('static/assets/img/sea.JPG')">
            <div class="container position-relative">
                <div class="justify-content-center">
                        <div class="page-heading">
                            <h1>LearnStock</h1>
                            <span >This is the best application for studying stock</span>
                    </div>
                </div>
            </div>
        </header>

        {% block body_block %}
        <!-- Main Content-->
        {% endblock %}

        <!-- Footer-->
        <footer class="border-top">
                <div class="justify-content-center">
                        <div class="text-center">Copyright &copy; LearnStock 2021</div>
                        <div class="text-center">For help, please contact Yueyue Liu </div>
                </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="static/js/scripts.js"></script>
    </body>
</html>

templates/stock/category.html
{% extends 'stock/base2.html' %}
{% load staticfiles %}

{% block title_block %}
   {% if category %}
       {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    <div style="text-align: center; width: 1350px; border: rgb(127, 193, 219) solid 5px;">
          {% if category %}
               <h1>{{ category.name }}</h1>
    </div>

    <div style="text-align:center">      
          <strong id="like_count">{{ category.likes }}</strong> likes                             
    </div>
                   
    <div style="background-color: beige;">
            {% if pages %}
            <ul >
               {% for page in pages %}
               <h4> 
                   <li>
                    <a href="{% url 'stock:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                    <!--if page.views>0,it will show the number of views-->
                          {% if page.views > 0 %}
                             <a> views:{{page.views }}</a>  
                    </li>
               </h4>
                           {% endif %}
            {% endfor %}
           
            </ul>
            {% else %}
                 <strong>No pages currently in category.</strong>
            {% endif %}
    </div>

<!----comments-->
    <div>
            {% if user.is_authenticated %}
                <a href="{% url 'stock:add_page' category.slug %}">
                   <div style="text-align: center">
                    <h3>Add Own Material Page</h3>
                   </div>
                </a> 
                <br />
            {% endif %}
            {% else %}
                     The specified category does not exist.
            {% endif %}
    </div>
            
    <div style=" background:bisque; width: 1350px; border: rgb(127, 193, 219) solid 5px;">
            <h3 class=>Comment Area</h3>
        <div>
            <!-- comment area -->
            {% if comments %}
            {% for comment in comments %}
        <div style="background-color: rgb(212, 212, 165);"class="media" id="comment-post">
                <div class>
                    {{ comment.username }}  @ {{ comment.posttime }}
                </div>
                    <h4> {{ comment.content }}</h4>
                                
        </div>
            {% endfor %}
            {% else %}
                        <p>There are not comments post currently.</p>
            {% endif %}
                  
            <!-- comment button -->
                {% if user.is_authenticated %}
            <form id="comment_form" method="post" action="{% url 'stock:add_comment' category.slug %}">
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                    {% endfor %}
            
                    {% for field in form.visible_fields %}
                            {{ field.errors }}
                            {{ field.help_text }}
                            {{ field }}
                    {% endfor %}
                <input type="submit" name="submit" value="Add Comment" class="btn btn-primary" />
            </form>
                    {% endif %}
            </div>
    </div>
  {% endblock %}
    

templates/stock/search.html
{% extends 'stock/base2.html' %}
{% load staticfiles %}
{% block title_block %}
       Search
{% endblock %}

{% block body_block %}
<div>
        <h1>Search with Stock</h1>
</div>

<div>
      <form class="form-inline" id="user-form" method="post" action="{% url 'stock:search' %}">
        {% csrf_token %}
        <div class="form-group">
        <input class="form-control" type="text" size="50" name="query" id="query" />
        </div>
           <button  type="submit" name="submit">Search</button> </form>
</div>

{% endblock %}